export const countryCodeList = [
  { label: "United Arab Emirates (AED)", value: "AED" },
  { label: "Afghanistan (AFN)", value: "AFN" },
  { label: "Albania (ALL)", value: "ALL" },
  { label: "Armenia (AMD)", value: "AMD" },
  { label: "Netherlands Antilles (ANG)", value: "ANG" },
  { label: "Angola (AOA)", value: "AOA" },
  { label: "Argentina (ARS)", value: "ARS" },
  { label: "Australia (AUD)", value: "AUD" },
  { label: "Aruba (AWG)", value: "AWG" },
  { label: "Azerbaijan (AZN)", value: "AZN" },
  { label: "Bosnia and Herzegovina (BAM)", value: "BAM" },
  { label: "Barbados (BBD)", value: "BBD" },
  { label: "Bangladesh (BDT)", value: "BDT" },
  { label: "Bulgaria (BGN)", value: "BGN" },
  { label: "Bahrain (BHD)", value: "BHD" },
  { label: "Burundi (BIF)", value: "BIF" },
  { label: "Bermuda (BMD)", value: "BMD" },
  { label: "Brunei Darussalam (BND)", value: "BND" },
  { label: "Bolivia (BOB)", value: "BOB" },
  { label: "Brazil (BRL)", value: "BRL" },
  { label: "Bahamas (BSD)", value: "BSD" },
  { label: "Bitcoin (BTC)", value: "BTC" },
  { label: "Bhutan (BTN)", value: "BTN" },
  { label: "Botswana (BWP)", value: "BWP" },
  { label: "Belarus (BYN)", value: "BYN" },
  { label: "Belize (BZD)", value: "BZD" },
  { label: "Canada (CAD)", value: "CAD" },
  { label: "Congo (CDF)", value: "CDF" },
  { label: "Switzerland (CHF)", value: "CHF" },
  { label: "Chile (CLF)", value: "CLF" },
  { label: "Chile (CLP)", value: "CLP" },
  { label: "China (CNH)", value: "CNH" },
  { label: "China (CNY)", value: "CNY" },
  { label: "Colombia (COP)", value: "COP" },
  { label: "Costa Rica (CRC)", value: "CRC" },
  { label: "Cuba (CUC)", value: "CUC" },
  { label: "Cuba (CUP)", value: "CUP" },
  { label: "Cape Verde (CVE)", value: "CVE" },
  { label: "Czech Republic (CZK)", value: "CZK" },
  { label: "Djibouti (DJF)", value: "DJF" },
  { label: "Denmark (DKK)", value: "DKK" },
  { label: "Dominican Republic (DOP)", value: "DOP" },
  { label: "Algeria (DZD)", value: "DZD" },
  { label: "Egypt (EGP)", value: "EGP" },
  { label: "Eritrea (ERN)", value: "ERN" },
  { label: "Ethiopia (ETB)", value: "ETB" },
  { label: "Euro Member Countries (EUR)", value: "EUR" },
  { label: "Fiji (FJD)", value: "FJD" },
  { label: "Falkland Islands (FKP)", value: "FKP" },
  { label: "United Kingdom (GBP)", value: "GBP" },
  { label: "Georgia (GEL)", value: "GEL" },
  { label: "Guernsey (GGP)", value: "GGP" },
  { label: "Ghana (GHS)", value: "GHS" },
  { label: "Gibraltar (GIP)", value: "GIP" },
  { label: "Gambia (GMD)", value: "GMD" },
  { label: "Guinea (GNF)", value: "GNF" },
  { label: "Guatemala (GTQ)", value: "GTQ" },
  { label: "Guyana (GYD)", value: "GYD" },
  { label: "Hong Kong (HKD)", value: "HKD" },
  { label: "Honduras (HNL)", value: "HNL" },
  { label: "Croatia (HRK)", value: "HRK" },
  { label: "Haiti (HTG)", value: "HTG" },
  { label: "Hungary (HUF)", value: "HUF" },
  { label: "Indonesia (IDR)", value: "IDR" },
  { label: "Israel (ILS)", value: "ILS" },
  { label: "Isle of Man (IMP)", value: "IMP" },
  { label: "India (INR)", value: "INR" },
  { label: "Iraq (IQD)", value: "IQD" },
  { label: "Iran (IRR)", value: "IRR" },
  { label: "Iceland (ISK)", value: "ISK" },
  { label: "Jersey (JEP)", value: "JEP" },
  { label: "Jamaica (JMD)", value: "JMD" },
  { label: "Jordan (JOD)", value: "JOD" },
  { label: "Japan (JPY)", value: "JPY" },
  { label: "Kenya (KES)", value: "KES" },
  { label: "Kyrgyzstan (KGS)", value: "KGS" },
  { label: "Cambodia (KHR)", value: "KHR" },
  { label: "Comoros (KMF)", value: "KMF" },
  { label: "North Korea (KPW)", value: "KPW" },
  { label: "South Korea (KRW)", value: "KRW" },
  { label: "Kuwait (KWD)", value: "KWD" },
  { label: "Cayman Islands (KYD)", value: "KYD" },
  { label: "Kazakhstan (KZT)", value: "KZT" },
  { label: "Laos (LAK)", value: "LAK" },
  { label: "Lebanon (LBP)", value: "LBP" },
  { label: "Sri Lanka (LKR)", value: "LKR" },
  { label: "Liberia (LRD)", value: "LRD" },
  { label: "Lesotho (LSL)", value: "LSL" },
  { label: "Libya (LYD)", value: "LYD" },
  { label: "Morocco (MAD)", value: "MAD" },
  { label: "Moldova (MDL)", value: "MDL" },
  { label: "Madagascar (MGA)", value: "MGA" },
  { label: "North Macedonia (MKD)", value: "MKD" },
  { label: "Myanmar (MMK)", value: "MMK" },
  { label: "Mongolia (MNT)", value: "MNT" },
  { label: "Macau (MOP)", value: "MOP" },
  { label: "Mauritania (MRO)", value: "MRO" },
  { label: "Mauritania (MRU)", value: "MRU" },
  { label: "Mauritius (MUR)", value: "MUR" },
  { label: "Maldives (MVR)", value: "MVR" },
  { label: "Malawi (MWK)", value: "MWK" },
  { label: "Mexico (MXN)", value: "MXN" },
  { label: "Malaysia (MYR)", value: "MYR" },
  { label: "Mozambique (MZN)", value: "MZN" },
  { label: "Namibia (NAD)", value: "NAD" },
  { label: "Nigeria (NGN)", value: "NGN" },
  { label: "Nicaragua (NIO)", value: "NIO" },
  { label: "Norway (NOK)", value: "NOK" },
  { label: "Nepal (NPR)", value: "NPR" },
  { label: "New Zealand (NZD)", value: "NZD" },
  { label: "Oman (OMR)", value: "OMR" },
  { label: "Panama (PAB)", value: "PAB" },
  { label: "Peru (PEN)", value: "PEN" },
  { label: "Papua New Guinea (PGK)", value: "PGK" },
  { label: "Philippines (PHP)", value: "PHP" },
  { label: "Pakistan (PKR)", value: "PKR" },
  { label: "Poland (PLN)", value: "PLN" },
  { label: "Paraguay (PYG)", value: "PYG" },
  { label: "Qatar (QAR)", value: "QAR" },
  { label: "Romania (RON)", value: "RON" },
  { label: "Serbia (RSD)", value: "RSD" },
  { label: "Russia (RUB)", value: "RUB" },
  { label: "Rwanda (RWF)", value: "RWF" },
  { label: "Saudi Arabia (SAR)", value: "SAR" },
  { label: "Solomon Islands (SBD)", value: "SBD" },
  { label: "Seychelles (SCR)", value: "SCR" },
  { label: "Sudan (SDG)", value: "SDG" },
  { label: "Sweden (SEK)", value: "SEK" },
  { label: "Singapore (SGD)", value: "SGD" },
  { label: "Saint Helena (SHP)", value: "SHP" },
  { label: "Sierra Leone (SLL)", value: "SLL" },
  { label: "Somalia (SOS)", value: "SOS" },
  { label: "Suriname (SRD)", value: "SRD" },
  { label: "South Sudan (SSP)", value: "SSP" },
  { label: "São Tomé and Príncipe (STD)", value: "STD" },
  { label: "São Tomé and Príncipe (STN)", value: "STN" },
  { label: "El Salvador (SVC)", value: "SVC" },
  { label: "Syria (SYP)", value: "SYP" },
  { label: "Eswatini (SZL)", value: "SZL" },
  { label: "Thailand (THB)", value: "THB" },
  { label: "Tajikistan (TJS)", value: "TJS" },
  { label: "Turkmenistan (TMT)", value: "TMT" },
  { label: "Tunisia (TND)", value: "TND" },
  { label: "Tonga (TOP)", value: "TOP" },
  { label: "Turkey (TRY)", value: "TRY" },
  { label: "Trinidad and Tobago (TTD)", value: "TTD" },
  { label: "Taiwan (TWD)", value: "TWD" },
  { label: "Tanzania (TZS)", value: "TZS" },
  { label: "Ukraine (UAH)", value: "UAH" },
  { label: "Uganda (UGX)", value: "UGX" },
  { label: "United States (USD)", value: "USD" },
  { label: "Uruguay (UYU)", value: "UYU" },
  { label: "Uzbekistan (UZS)", value: "UZS" },
  { label: "Venezuela (VEF)", value: "VEF" },
  { label: "Venezuela (VES)", value: "VES" },
  { label: "Vietnam (VND)", value: "VND" },
  { label: "Vanuatu (VUV)", value: "VUV" },
  { label: "Samoa (WST)", value: "WST" },
  { label: "Central African CFA (XAF)", value: "XAF" },
  { label: "Silver Ounce (XAG)", value: "XAG" },
  { label: "Gold Ounce (XAU)", value: "XAU" },
  { label: "East Caribbean Dollar (XCD)", value: "XCD" },
  { label: "IMF Special Drawing Rights (XDR)", value: "XDR" },
  { label: "West African CFA (XOF)", value: "XOF" },
  { label: "Palladium Ounce (XPD)", value: "XPD" },
  { label: "CFP Franc (XPF)", value: "XPF" },
  { label: "Platinum Ounce (XPT)", value: "XPT" },
  { label: "Yemen (YER)", value: "YER" },
  { label: "South Africa (ZAR)", value: "ZAR" },
  { label: "Zambia (ZMW)", value: "ZMW" },
  { label: "Zimbabwe (ZWL)", value: "ZWL" }
];